### ISSUE TITLE
Lorax server hangs on warming up the server when total_tokens is larger than 4096 with LLama2-7b-hf on a l4 GPU

### ISSUE THREAD

**Issue by martinbomio** [predibase/lorax#334]
### System Info

These are the params I am using to start the lorax server (in GKE):
```
        - '--model-id=meta-llama/Llama-2-7b-hf'
        - '--revision=8cca527612d856d7d32bd94f8103728d614eb852'
        - '--source=hub'
        # greater than the max input tokens we will use in the benchmarks
        - '--max-input-length=1048'
        # greater than the sum of max output tokens + max input tokens
        # for any benchmark. The max we have is 512 input tokens + 3584 output tokens
        - '--max-total-tokens=4096'
        - '--max-batch-prefill-tokens=2048'
        # run on a single GPU for now
        - '--num-shard=1'
        - '--cuda-memory-fraction=0.9'
        - '--port=8080'
 ```

Running it on a single L4 GPU.
Using `ghcr.io/predibase/lorax:latest` image

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

1. Use the following manifest and deploy it to kubernetes:
```
apiVersion: v1
kind: Pod
metadata:
  name: lorax
  namespace: namespace
  labels:
    owner: owner
    app: lorax
spec:
  containers:
    - name: lorax
      image: ghcr.io/predibase/lorax:latest
      env:
        - name: HUGGING_FACE_HUB_TOKEN
          value: ...
      args:
        - '--model-id=meta-llama/Llama-2-7b-hf'
        - '--revision=8cca527612d856d7d32bd94f8103728d614eb852'
        - '--source=hub'
        - '--max-input-length=1048'
        - '--max-total-tokens=4096'
        - '--max-batch-prefill-tokens=2048'
        - '--num-shard=1'
        - '--cuda-memory-fraction=0.9'
        - '--port=8080'
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 10
      resources:
        requests:
          cpu: 6
          memory: 16G
        limits:
          cpu: 6
          memory: 16G
          nvidia.com/gpu: 1
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
  nodeSelector:
    <select the l4 node pool>
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 1G

```
2. Check the logs of the pod with: 
```
kubectl -n namespace  logs lorax -f  
```
and the last lines in shows are:
```
2024-03-15T20:10:41.488484Z  INFO lorax_router: router/src/main.rs:465: Serving revision 8cca527612d856d7d32bd94f8103728d614eb852 of model meta-llama/Llama-2-7b-hf
2024-03-15T20:10:41.502080Z  INFO lorax_router: router/src/main.rs:296: Warming up model
```

### Expected behavior

It should start serving the model.

If we look at the GPU stats, it doesn't seem to be using it, and the memory seems on bounds:
```
[0] NVIDIA L4 | 67°C,   0 % | 19048 / 23034 MB |
```
